// ─── Shared Property Types ────────────────────────────────────────────────────

export interface Room {
    id: string
    name: string
    maxGuests: number
    bedType: string
    sqft: number
    pricePerNight: number
    originalPrice?: number
    tag?: "Refundable" | "Popular" | "Last rooms"
    features: string[]
    imageSrc: string
}

export interface Review {
    id: string
    author: string
    avatarInitials: string
    avatarColor: string
    date: string
    text: string
    rating: number
}

export interface PropertyDetail {
    id: string
    title: string
    location: string
    fullAddress: string
    propertyType: string
    pricePerNight: number
    rating: number
    reviewCount: number
    badge?: "Superhost" | "Guest favorite"
    imageSrc: string        // primary / card image
    galleryImages: string[] // 4 extra images for gallery grid

    // Host
    hostName: string
    hostBio: string
    hostYears: number
    hostSuperhost: boolean

    // Description
    description: string

    // Amenities
    amenities: { icon: string; label: string }[]

    // Reviews breakdown
    reviewBreakdown: { label: string; score: number }[]
    reviews: Review[]

    // Rooms
    rooms: Room[]

    // Map coords (for embed)
    lat: number
    lng: number
}

// ─── Amenity icon names (Lucide) ─────────────────────────────────────────────
// We store them as strings and resolve in the UI with a lookup map.

// ─── All 12 Properties ────────────────────────────────────────────────────────

export const ALL_PROPERTIES: PropertyDetail[] = [
    {
        id: "1",
        title: "Colombo Sky Residency",
        location: "Colombo 3",
        fullAddress: "32 Galle Road, Colombo 03, Sri Lanka",
        propertyType: "Apartment",
        pricePerNight: 25_000,
        rating: 4.92,
        reviewCount: 148,
        badge: "Superhost",
        imageSrc: "/images/properties/property-1.jpg",
        galleryImages: [
            "/images/properties/property-2.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-4.jpg",
            "/images/properties/property-5.jpg",
        ],
        hostName: "Priya Fernando",
        hostBio: "Superhost · 5 years experience · Member since 2019",
        hostYears: 5,
        hostSuperhost: true,
        description:
            "Experience Colombo's vibrant city life from this sleek sky-high apartment in the heart of Colombo 3. Floor-to-ceiling windows frame panoramic views of the Indian Ocean and the city skyline. Designed with minimalist luxury in mind, every room features Italian marble accents, smart-home controls, and curated Sri Lankan artwork. Steps away from Galle Face Green, world-class restaurants, and the city's best shopping.",
        amenities: [
            { icon: "Wifi", label: "Free High Speed WiFi" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Waves", label: "Rooftop Pool" },
            { icon: "Dumbbell", label: "Fitness Center" },
            { icon: "Car", label: "Valet Parking" },
            { icon: "Utensils", label: "In-suite Kitchen" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Coffee", label: "Nespresso Machine" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 4.9 },
            { label: "Service", score: 4.8 },
            { label: "Location", score: 5.0 },
        ],
        reviews: [
            {
                id: "r1",
                author: "Marco Rossi",
                avatarInitials: "MR",
                avatarColor: "#953002",
                date: "2 months ago",
                text: "Incredible stay. The staff was attentive and the location is unbeatable. The rooftop views are even better in person!",
                rating: 5,
            },
            {
                id: "r2",
                author: "Sarah Jenkins",
                avatarInitials: "SJ",
                avatarColor: "#2E7D32",
                date: "3 weeks ago",
                text: "The spa facilities are top-notch. I highly recommend the deluxe suite for the extra space. Worth every penny.",
                rating: 5,
            },
            {
                id: "r3",
                author: "Anura Perera",
                avatarInitials: "AP",
                avatarColor: "#1565C0",
                date: "1 month ago",
                text: "Perfect apartment for a business trip. WiFi is blazing fast, kitchen has everything you need, and the concierge was very helpful.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-1-1",
                name: "Deluxe Ocean View Room",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 480,
                pricePerNight: 25_000,
                originalPrice: 28_000,
                tag: "Refundable",
                features: ["Private Balcony", "Nespresso Machine"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
            {
                id: "room-1-2",
                name: "Panoramic Grand Suite",
                maxGuests: 4,
                bedType: "2 Queen Beds",
                sqft: 650,
                pricePerNight: 35_000,
                tag: "Popular",
                features: ["Floor-to-ceiling windows", "Separate living area"],
                imageSrc: "/images/rooms/room-grand-suite.jpg",
            },
            {
                id: "room-1-3",
                name: "Sky Penthouse",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 900,
                pricePerNight: 55_000,
                features: ["Private terrace", "Marble bathroom", "Butler service"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
        ],
        lat: 6.9088,
        lng: 79.8543,
    },
    {
        id: "2",
        title: "Galle Fort Heritage Cottage",
        location: "Galle Fort",
        fullAddress: "14 Church St, Galle Fort, Sri Lanka",
        propertyType: "Guesthouse",
        pricePerNight: 35_000,
        rating: 4.85,
        reviewCount: 92,
        imageSrc: "/images/properties/property-2.jpg",
        galleryImages: [
            "/images/properties/property-1.jpg",
            "/images/properties/property-4.jpg",
            "/images/properties/property-6.jpg",
            "/images/properties/property-8.jpg",
        ],
        hostName: "Chamari De Silva",
        hostBio: "Superhost · 7 years experience · Member since 2017",
        hostYears: 7,
        hostSuperhost: true,
        description:
            "Step back in time in this beautifully restored Dutch colonial cottage within the UNESCO-listed Galle Fort. Original 18th-century architecture blends seamlessly with modern comfort — antique wooden beams, hand-crafted furniture, and a lush courtyard garden. Walk seconds to the fort's ramparts for spectacular Indian Ocean sunsets.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "BookOpen", label: "Library" },
            { icon: "Coffee", label: "Garden Café" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Bike", label: "Bicycle Rental" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 4.9 },
            { label: "Atmosphere", score: 5.0 },
            { label: "Location", score: 5.0 },
        ],
        reviews: [
            {
                id: "r2-1",
                author: "Emma Watson",
                avatarInitials: "EW",
                avatarColor: "#6A1B9A",
                date: "1 month ago",
                text: "Absolutely magical. Waking up inside the fort and strolling to the ramparts at sunrise is an experience I'll never forget.",
                rating: 5,
            },
            {
                id: "r2-2",
                author: "James Liu",
                avatarInitials: "JL",
                avatarColor: "#00695C",
                date: "2 months ago",
                text: "The cottage is even more charming than the photos. Chamari was an exceptional host — so many great local tips!",
                rating: 5,
            },
            {
                id: "r2-3",
                author: "Nalini Iyer",
                avatarInitials: "NI",
                avatarColor: "#AD1457",
                date: "3 weeks ago",
                text: "Perfect base for exploring Galle. The courtyard breakfast with fresh papaya and hoppers was divine.",
                rating: 4,
            },
        ],
        rooms: [
            {
                id: "room-2-1",
                name: "Heritage Garden Room",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 320,
                pricePerNight: 35_000,
                originalPrice: 42_000,
                tag: "Refundable",
                features: ["Courtyard access", "Antique furnishings"],
                imageSrc: "/images/rooms/room-heritage.jpg",
            },
            {
                id: "room-2-2",
                name: "Fort View Loft",
                maxGuests: 2,
                bedType: "1 Queen Bed",
                sqft: 280,
                pricePerNight: 40_000,
                tag: "Popular",
                features: ["Fort wall views", "Skylight bathroom"],
                imageSrc: "/images/rooms/room-heritage.jpg",
            },
        ],
        lat: 6.0328,
        lng: 80.2170,
    },
    {
        id: "3",
        title: "Kandy Hilltop Luxury Villa",
        location: "Kandy",
        fullAddress: "7 Rajapihilla Mawatha, Kandy, Sri Lanka",
        propertyType: "Villa",
        pricePerNight: 75_000,
        rating: 5.0,
        reviewCount: 67,
        badge: "Guest favorite",
        imageSrc: "/images/properties/property-3.jpg",
        galleryImages: [
            "/images/properties/property-1.jpg",
            "/images/properties/property-7.jpg",
            "/images/properties/property-9.jpg",
            "/images/properties/property-11.jpg",
        ],
        hostName: "Roshan Mendis",
        hostBio: "Superhost · 6 years experience · Member since 2018",
        hostYears: 6,
        hostSuperhost: false,
        description:
            "Perched above the misty hills overlooking the sacred Kandy Lake and the Temple of the Tooth, this private luxury villa offers an unparalleled blend of nature and elegance. With infinity pool, private chef, and butler service, every detail is curated for the discerning traveller. Lush gardens filled with tropical birds surround the property.",
        amenities: [
            { icon: "Wifi", label: "Free High Speed WiFi" },
            { icon: "Waves", label: "Infinity Pool" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Utensils", label: "Private Chef" },
            { icon: "Car", label: "Chauffeur Service" },
            { icon: "Dumbbell", label: "Yoga Pavilion" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Coffee", label: "Butler Service" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 5.0 },
            { label: "Service", score: 5.0 },
            { label: "Location", score: 5.0 },
        ],
        reviews: [
            {
                id: "r3-1",
                author: "Sophie Martin",
                avatarInitials: "SM",
                avatarColor: "#E65100",
                date: "1 month ago",
                text: "Genuinely the most beautiful place I've ever stayed. The lake views from the infinity pool are beyond words.",
                rating: 5,
            },
            {
                id: "r3-2",
                author: "David Park",
                avatarInitials: "DP",
                avatarColor: "#1565C0",
                date: "2 months ago",
                text: "Private chef prepared incredible Sri Lankan feasts every evening. The villa exceeded every expectation.",
                rating: 5,
            },
            {
                id: "r3-3",
                author: "Nuwan Silva",
                avatarInitials: "NS",
                avatarColor: "#2E7D32",
                date: "3 weeks ago",
                text: "Perfect honeymoon destination. Roshan arranged everything seamlessly — city tours, temple visits, tea estates.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-3-1",
                name: "Master Lake View Suite",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 700,
                pricePerNight: 75_000,
                originalPrice: 90_000,
                tag: "Popular",
                features: ["Lake-facing balcony", "Rain shower", "Bathtub"],
                imageSrc: "/images/rooms/room-grand-suite.jpg",
            },
            {
                id: "room-3-2",
                name: "Garden Pavilion Suite",
                maxGuests: 4,
                bedType: "2 King Beds",
                sqft: 950,
                pricePerNight: 120_000,
                features: ["Private garden", "Outdoor soaking tub", "Kitchenette"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
        ],
        lat: 7.2906,
        lng: 80.6337,
    },
    {
        id: "4",
        title: "Colombo Boutique Business Suite",
        location: "Colombo 7",
        fullAddress: "18 Ward Place, Colombo 07, Sri Lanka",
        propertyType: "Apartment",
        pricePerNight: 85_000,
        rating: 4.75,
        reviewCount: 53,
        imageSrc: "/images/properties/property-4.jpg",
        galleryImages: [
            "/images/properties/property-1.jpg",
            "/images/properties/property-2.jpg",
            "/images/properties/property-5.jpg",
            "/images/properties/property-11.jpg",
        ],
        hostName: "Dilrukshi Jayawardena",
        hostBio: "Superhost · 4 years experience · Member since 2020",
        hostYears: 4,
        hostSuperhost: false,
        description:
            "A refined urban retreat in the prestigious Colombo 7 enclave, designed for the modern business traveller. The suite features a dedicated workspace, ultra-fast fibre internet, and seamless access to Colombo's diplomatic and commercial district. Premium ergonomic furniture, video-conferencing setup, and 24-hour concierge ensure a flawless stay.",
        amenities: [
            { icon: "Wifi", label: "Gigabit WiFi" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Monitor", label: "Work Desk & Monitor" },
            { icon: "Coffee", label: "Nespresso Machine" },
            { icon: "Car", label: "Parking" },
            { icon: "ShieldCheck", label: "24hr Security" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 4.8 },
            { label: "Service", score: 4.7 },
            { label: "Location", score: 4.9 },
        ],
        reviews: [
            {
                id: "r4-1",
                author: "Peter Schmidt",
                avatarInitials: "PS",
                avatarColor: "#4527A0",
                date: "1 month ago",
                text: "Best work-from-hotel setup I've encountered in Asia. The monitor and standing desk were genuinely useful.",
                rating: 5,
            },
            {
                id: "r4-2",
                author: "Yasmin Al-Rashid",
                avatarInitials: "YA",
                avatarColor: "#00695C",
                date: "6 weeks ago",
                text: "Quiet, clean, and professional. Exactly what I needed for my conference week in Colombo.",
                rating: 4,
            },
        ],
        rooms: [
            {
                id: "room-4-1",
                name: "Executive Business Suite",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 520,
                pricePerNight: 85_000,
                tag: "Refundable",
                features: ["Dual monitor setup", "Standing desk", "Meeting table for 4"],
                imageSrc: "/images/rooms/room-executive.jpg",
            },
        ],
        lat: 6.9060,
        lng: 79.8605,
    },
    {
        id: "5",
        title: "Negombo Beachside Retreat",
        location: "Negombo",
        fullAddress: "78 Lewis Place, Negombo, Sri Lanka",
        propertyType: "Hotel",
        pricePerNight: 95_000,
        rating: 4.98,
        reviewCount: 211,
        badge: "Superhost",
        imageSrc: "/images/properties/property-5.jpg",
        galleryImages: [
            "/images/properties/property-7.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-6.jpg",
            "/images/properties/property-12.jpg",
        ],
        hostName: "Ravi Gunawardena",
        hostBio: "Superhost · 8 years experience · Member since 2016",
        hostYears: 8,
        hostSuperhost: true,
        description:
            "Wake up to the sound of waves at this stunning beachside boutique hotel on Negombo's golden coast — just 10 minutes from Bandaranaike International Airport. The property features lush tropical gardens, a beachfront infinity pool, and direct beach access. Fresh seafood from the daily catch is served at our acclaimed open-air restaurant.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Waves", label: "Beachfront Pool" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Utensils", label: "Seafood Restaurant" },
            { icon: "Bike", label: "Bicycle Rental" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Dumbbell", label: "Gym" },
            { icon: "Car", label: "Airport Shuttle" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 5.0 },
            { label: "Service", score: 5.0 },
            { label: "Beach Access", score: 5.0 },
        ],
        reviews: [
            {
                id: "r5-1",
                author: "Claire Dubois",
                avatarInitials: "CD",
                avatarColor: "#C62828",
                date: "2 weeks ago",
                text: "Perfect start to our Sri Lanka trip. After midnight flight, we had a seamless airport pickup and woke to this gorgeous beach.",
                rating: 5,
            },
            {
                id: "r5-2",
                author: "Tariq Hassan",
                avatarInitials: "TH",
                avatarColor: "#1B5E20",
                date: "1 month ago",
                text: "The grilled lobster at the beach restaurant was the best I've ever had. Ravi's hospitality is extraordinary.",
                rating: 5,
            },
            {
                id: "r5-3",
                author: "Mei Lin",
                avatarInitials: "ML",
                avatarColor: "#880E4F",
                date: "3 weeks ago",
                text: "Incredible sunsets from the infinity pool. The beach chairs are set up perfectly — we practically lived on them.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-5-1",
                name: "Beachfront Deluxe Room",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 450,
                pricePerNight: 95_000,
                originalPrice: 115_000,
                tag: "Last rooms",
                features: ["Direct beach access", "Outdoor shower"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
            {
                id: "room-5-2",
                name: "Garden Pool Villa",
                maxGuests: 4,
                bedType: "2 Queen Beds",
                sqft: 750,
                pricePerNight: 150_000,
                tag: "Popular",
                features: ["Private plunge pool", "Outdoor dining"],
                imageSrc: "/images/rooms/room-grand-suite.jpg",
            },
        ],
        lat: 7.2083,
        lng: 79.8358,
    },
    {
        id: "6",
        title: "Ella Mountain Eco Cabin",
        location: "Ella",
        fullAddress: "Ella Gap Road, Ella, Sri Lanka",
        propertyType: "Villa",
        pricePerNight: 45_000,
        rating: 4.88,
        reviewCount: 134,
        imageSrc: "/images/properties/property-6.jpg",
        galleryImages: [
            "/images/properties/property-9.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-11.jpg",
            "/images/properties/property-7.jpg",
        ],
        hostName: "Nimal Rathnayake",
        hostBio: "Eco host · 4 years experience · Member since 2020",
        hostYears: 4,
        hostSuperhost: false,
        description:
            "Nestled within a working tea estate high above the famous Ella Gap, this sustainably-built eco cabin offers complete immersion in Sri Lanka's central highlands. Solar powered, rainwater harvested, and zero-plastic, the cabin lets you reconnect with nature without compromise. Wake up to misty mountain scenes, fireflies at night, and the melody of birdsong at dawn.",
        amenities: [
            { icon: "Wifi", label: "Solar WiFi" },
            { icon: "Leaf", label: "Eco/Solar Power" },
            { icon: "Coffee", label: "Tea Plantation Tour" },
            { icon: "Utensils", label: "Farm-to-table Meals" },
            { icon: "Bike", label: "Hiking Trails" },
            { icon: "ShieldCheck", label: "Night Security" },
        ],
        reviewBreakdown: [
            { label: "Sustainability", score: 5.0 },
            { label: "Atmosphere", score: 5.0 },
            { label: "Cleanliness", score: 4.7 },
        ],
        reviews: [
            {
                id: "r6-1",
                author: "Oliver Green",
                avatarInitials: "OG",
                avatarColor: "#2E7D32",
                date: "1 month ago",
                text: "Pure magic. Woke up at 5am for the sunrise over Ella Gap and it was life-changing. The farm breakfast seals the deal.",
                rating: 5,
            },
            {
                id: "r6-2",
                author: "Aisha Patel",
                avatarInitials: "AP",
                avatarColor: "#6A1B9A",
                date: "2 months ago",
                text: "As eco-conscious travellers we loved the zero-waste setup. The tea estate walk with Nimal was deeply educational.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-6-1",
                name: "Tea Estate Cabin",
                maxGuests: 2,
                bedType: "1 Queen Bed",
                sqft: 280,
                pricePerNight: 45_000,
                originalPrice: 55_000,
                tag: "Refundable",
                features: ["Mountain-view deck", "Outdoor shower", "Hammock"],
                imageSrc: "/images/rooms/room-eco-cabin.jpg",
            },
        ],
        lat: 6.8728,
        lng: 81.0466,
    },
    {
        id: "7",
        title: "Mirissa Oceanfront Villa",
        location: "Mirissa",
        fullAddress: "Mirissa Bay Road, Mirissa, Sri Lanka",
        propertyType: "Villa",
        pricePerNight: 120_000,
        rating: 4.96,
        reviewCount: 88,
        badge: "Guest favorite",
        imageSrc: "/images/properties/property-7.jpg",
        galleryImages: [
            "/images/properties/property-5.jpg",
            "/images/properties/property-12.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-8.jpg",
        ],
        hostName: "Saman Wickramasinghe",
        hostBio: "Superhost · 6 years experience · Member since 2018",
        hostYears: 6,
        hostSuperhost: true,
        description:
            "Sri Lanka's most iconic oceanfront villa — positioned directly on Mirissa's crescent bay with uninterrupted 180° views of the Indian Ocean. Spot blue whales from the infinity pool (November–April season), watch the world's best surfers from your private terrace, and fall asleep to the rhythm of waves. A private tropical paradise with full staff.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Waves", label: "Ocean-edge Infinity Pool" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Utensils", label: "Private Chef" },
            { icon: "Car", label: "Airport Transfer" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Dumbbell", label: "Yoga Deck" },
            { icon: "Coffee", label: "Butler on call" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 5.0 },
            { label: "Service", score: 5.0 },
            { label: "Ocean Views", score: 5.0 },
        ],
        reviews: [
            {
                id: "r7-1",
                author: "Isabella Torres",
                avatarInitials: "IT",
                avatarColor: "#E65100",
                date: "3 weeks ago",
                text: "We saw THREE blue whales from the pool. The chef's seafood curry was otherworldly. Simply the best vacation of my life.",
                rating: 5,
            },
            {
                id: "r7-2",
                author: "Kenji Tanaka",
                avatarInitials: "KT",
                avatarColor: "#C62828",
                date: "2 months ago",
                text: "Worth every rupee. The staff anticipated every need before we even asked. The sunset views are indescribable.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-7-1",
                name: "Ocean Master Suite",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 650,
                pricePerNight: 120_000,
                originalPrice: 145_000,
                tag: "Popular",
                features: ["Sea-facing terrace", "Rain shower", "Soaking tub"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
            {
                id: "room-7-2",
                name: "Coral Bay Villa",
                maxGuests: 6,
                bedType: "3 King Beds",
                sqft: 1200,
                pricePerNight: 250_000,
                features: ["Entire lower villa", "Private beach access", "Chef included"],
                imageSrc: "/images/rooms/room-grand-suite.jpg",
            },
        ],
        lat: 5.9488,
        lng: 80.4593,
    },
    {
        id: "8",
        title: "Galle Dutch Period Mansion",
        location: "Galle Fort",
        fullAddress: "22 Leyn Baan Street, Galle Fort, Sri Lanka",
        propertyType: "Villa",
        pricePerNight: 180_000,
        rating: 4.91,
        reviewCount: 45,
        badge: "Superhost",
        imageSrc: "/images/properties/property-8.jpg",
        galleryImages: [
            "/images/properties/property-2.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-6.jpg",
            "/images/properties/property-9.jpg",
        ],
        hostName: "Anjalee Perera",
        hostBio: "Superhost · 9 years experience · Member since 2015",
        hostYears: 9,
        hostSuperhost: true,
        description:
            "A masterwork of 18th-century Dutch colonial architecture — fully restored and appointed with museum-quality antiques, hand-woven tapestries, and original Portuguese tile floors. This grand mansion within the Galle Fort walls offers six luxurious suites, a private courtyard pool, and a celebrated heritage restaurant. Featured in Condé Nast Traveller.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Waves", label: "Courtyard Pool" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Utensils", label: "Heritage Restaurant" },
            { icon: "BookOpen", label: "Antique Library" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Coffee", label: "Butler Service" },
            { icon: "Car", label: "Chauffeur" },
        ],
        reviewBreakdown: [
            { label: "Cleanliness", score: 4.9 },
            { label: "Heritage Value", score: 5.0 },
            { label: "Service", score: 4.8 },
        ],
        reviews: [
            {
                id: "r8-1",
                author: "Charlotte Hughes",
                avatarInitials: "CH",
                avatarColor: "#4527A0",
                date: "1 month ago",
                text: "The most atmospheric property I've ever stayed in. Dining by candlelight in a 300-year-old courtyard is something else entirely.",
                rating: 5,
            },
            {
                id: "r8-2",
                author: "Ravi Menon",
                avatarInitials: "RM",
                avatarColor: "#1565C0",
                date: "2 months ago",
                text: "Anjalee has turned this mansion into a living museum. Every room tells a story. Absolute bucket-list accommodation.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-8-1",
                name: "Dutch Governor's Suite",
                maxGuests: 2,
                bedType: "1 King Canopy Bed",
                sqft: 800,
                pricePerNight: 180_000,
                originalPrice: 210_000,
                tag: "Last rooms",
                features: ["Courtyard views", "Original tile floors", "Clawfoot bathtub"],
                imageSrc: "/images/rooms/room-heritage.jpg",
            },
            {
                id: "room-8-2",
                name: "Rampart View Room",
                maxGuests: 2,
                bedType: "1 Queen Bed",
                sqft: 420,
                pricePerNight: 120_000,
                tag: "Refundable",
                features: ["Fort wall views", "Antique writing desk"],
                imageSrc: "/images/rooms/room-heritage.jpg",
            },
        ],
        lat: 6.0309,
        lng: 80.2157,
    },
    {
        id: "9",
        title: "Nuwara Eliya Tea Planter's Bungalow",
        location: "Nuwara Eliya",
        fullAddress: "St Andrew's Drive, Nuwara Eliya, Sri Lanka",
        propertyType: "Guesthouse",
        pricePerNight: 65_000,
        rating: 4.82,
        reviewCount: 109,
        imageSrc: "/images/properties/property-9.jpg",
        galleryImages: [
            "/images/properties/property-6.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-11.jpg",
            "/images/properties/property-4.jpg",
        ],
        hostName: "Victor Steuart",
        hostBio: "Heritage host · 11 years experience · Member since 2013",
        hostYears: 11,
        hostSuperhost: false,
        description:
            "A colonial-era tea planter's bungalow set amid 400 acres of pristine tea gardens at 6,000 feet. The chill of 'Little England' greets you at the door — log fires, tartan armchairs, and silver tea service await. Tour the estate with the head planter, visit the factory, and savour high tea overlooking the misty Horton Plains.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Coffee", label: "Silver Tea Service" },
            { icon: "Wind", label: "Fireplace" },
            { icon: "Utensils", label: "Colonial Dining" },
            { icon: "Bike", label: "Estate Walks" },
            { icon: "ShieldCheck", label: "Night Security" },
        ],
        reviewBreakdown: [
            { label: "Ambience", score: 5.0 },
            { label: "Cleanliness", score: 4.7 },
            { label: "Location", score: 4.8 },
        ],
        reviews: [
            {
                id: "r9-1",
                author: "George Mitchell",
                avatarInitials: "GM",
                avatarColor: "#37474F",
                date: "6 weeks ago",
                text: "Felt like being transported to 1920s Ceylon. The afternoon tea on the veranda watching the tea pickers was unforgettable.",
                rating: 5,
            },
            {
                id: "r9-2",
                author: "Kumari Wickrama",
                avatarInitials: "KW",
                avatarColor: "#AD1457",
                date: "2 months ago",
                text: "Victor is a wonderful storyteller. His knowledge of the estate's history made every tour fascinating.",
                rating: 4,
            },
        ],
        rooms: [
            {
                id: "room-9-1",
                name: "Planter's Master Bedroom",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 500,
                pricePerNight: 65_000,
                tag: "Popular",
                features: ["Estate views", "Log fireplace", "Claw-foot bathtub"],
                imageSrc: "/images/rooms/room-heritage.jpg",
            },
            {
                id: "room-9-2",
                name: "Garden Cottage Room",
                maxGuests: 2,
                bedType: "1 Double Bed",
                sqft: 280,
                pricePerNight: 45_000,
                tag: "Refundable",
                features: ["Garden views", "Heated floors"],
                imageSrc: "/images/rooms/room-eco-cabin.jpg",
            },
        ],
        lat: 6.9497,
        lng: 80.7891,
    },
    {
        id: "10",
        title: "Arugam Bay Surf House",
        location: "Arugam Bay",
        fullAddress: "Main Beach Road, Arugam Bay, Sri Lanka",
        propertyType: "Guesthouse",
        pricePerNight: 28_000,
        rating: 4.79,
        reviewCount: 176,
        imageSrc: "/images/properties/property-10.jpg",
        galleryImages: [
            "/images/properties/property-5.jpg",
            "/images/properties/property-7.jpg",
            "/images/properties/property-12.jpg",
            "/images/properties/property-6.jpg",
        ],
        hostName: "Kapila Abeysekara",
        hostBio: "Surf host · 6 years experience · Member since 2018",
        hostYears: 6,
        hostSuperhost: false,
        description:
            "The go-to surfers' base camp at Arugam Bay — one of the world's top 10 surf destinations. Steps from Main Point break, this relaxed guesthouse with hammocks, home-cooked Sri Lankan meals, and surf gear rental attracts a global community of wave-riders. Kapila is a certified surf instructor offering all skill levels.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Waves", label: "Surf Board Rental" },
            { icon: "Wind", label: "Ceiling Fans" },
            { icon: "Utensils", label: "Sri Lankan Kitchen" },
            { icon: "Bike", label: "Bicycle Rental" },
            { icon: "Coffee", label: "Rooftop Chill Zone" },
        ],
        reviewBreakdown: [
            { label: "Vibe", score: 5.0 },
            { label: "Surf Access", score: 5.0 },
            { label: "Cleanliness", score: 4.6 },
        ],
        reviews: [
            {
                id: "r10-1",
                author: "Jake Morrison",
                avatarInitials: "JM",
                avatarColor: "#00695C",
                date: "3 weeks ago",
                text: "Best surf trip of my life. Kapila is a brilliant instructor — I went from beginner to catching real waves in 3 days.",
                rating: 5,
            },
            {
                id: "r10-2",
                author: "Priya Nair",
                avatarInitials: "PN",
                avatarColor: "#880E4F",
                date: "1 month ago",
                text: "The rice and curry breakfasts were incredible. Great atmosphere — met travellers from 15 different countries.",
                rating: 4,
            },
        ],
        rooms: [
            {
                id: "room-10-1",
                name: "Surf Dorm Bunk",
                maxGuests: 1,
                bedType: "Bunk Bed",
                sqft: 120,
                pricePerNight: 12_000,
                tag: "Refundable",
                features: ["Locker storage", "Shared bathroom"],
                imageSrc: "/images/rooms/room-eco-cabin.jpg",
            },
            {
                id: "room-10-2",
                name: "Private Surf Room",
                maxGuests: 2,
                bedType: "1 Queen Bed",
                sqft: 220,
                pricePerNight: 28_000,
                tag: "Popular",
                features: ["Ensuite bathroom", "Board storage"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
        ],
        lat: 6.8396,
        lng: 81.8362,
    },
    {
        id: "11",
        title: "Sigiriya Rock View Lodge",
        location: "Sigiriya",
        fullAddress: "Sigiriya Village Road, Sigiriya, Sri Lanka",
        propertyType: "Hotel",
        pricePerNight: 55_000,
        rating: 4.94,
        reviewCount: 203,
        badge: "Guest favorite",
        imageSrc: "/images/properties/property-11.jpg",
        galleryImages: [
            "/images/properties/property-3.jpg",
            "/images/properties/property-9.jpg",
            "/images/properties/property-6.jpg",
            "/images/properties/property-1.jpg",
        ],
        hostName: "Buddhika Kularatne",
        hostBio: "Superhost · 7 years experience · Member since 2017",
        hostYears: 7,
        hostSuperhost: true,
        description:
            "Gaze upon the awe-inspiring Sigiriya Rock Fortress — a UNESCO World Heritage Site — directly from your room. This boutique lodge is set within a tropical garden, with an infinity pool perfectly aligned to frame the ancient citadel. Cultural immersion experiences, sunrise hot-air balloon rides, and village cycling tours are arranged daily.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Waves", label: "Sigiriya-view Pool" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Utensils", label: "Garden Restaurant" },
            { icon: "Bike", label: "Cycling Tours" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Coffee", label: "Sunrise Ballon Rides" },
        ],
        reviewBreakdown: [
            { label: "Views", score: 5.0 },
            { label: "Cleanliness", score: 4.9 },
            { label: "Service", score: 4.9 },
        ],
        reviews: [
            {
                id: "r11-1",
                author: "Amelia Foster",
                avatarInitials: "AF",
                avatarColor: "#C62828",
                date: "2 weeks ago",
                text: "I woke at 5am to climb Sigiriya at sunrise — and then soaked in the pool staring at it from the other side. 10/10.",
                rating: 5,
            },
            {
                id: "r11-2",
                author: "Hiroshi Yamada",
                avatarInitials: "HY",
                avatarColor: "#1565C0",
                date: "1 month ago",
                text: "The hot-air balloon at dawn over the Cultural Triangle was an experience I will carry for the rest of my life.",
                rating: 5,
            },
            {
                id: "r11-3",
                author: "Monica De Bruin",
                avatarInitials: "MB",
                avatarColor: "#4527A0",
                date: "3 weeks ago",
                text: "Buddhika organised a private village tour that gave us a real insight into rural Sri Lankan life. Genuinely moved.",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-11-1",
                name: "Rock View Deluxe Room",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 380,
                pricePerNight: 55_000,
                originalPrice: 68_000,
                tag: "Popular",
                features: ["Sigiriya-facing window", "Garden terrace"],
                imageSrc: "/images/rooms/room-grand-suite.jpg",
            },
            {
                id: "room-11-2",
                name: "Garden Pool Bungalow",
                maxGuests: 4,
                bedType: "2 Queen Beds",
                sqft: 620,
                pricePerNight: 85_000,
                tag: "Refundable",
                features: ["Private plunge pool", "Outdoor dining area"],
                imageSrc: "/images/rooms/room-ocean-king.jpg",
            },
        ],
        lat: 7.9570,
        lng: 80.7603,
    },
    {
        id: "12",
        title: "Bentota Lagoon Water Villa",
        location: "Bentota",
        fullAddress: "Bentota Lagoon Drive, Bentota, Sri Lanka",
        propertyType: "Villa",
        pricePerNight: 90_000,
        rating: 4.87,
        reviewCount: 61,
        imageSrc: "/images/properties/property-12.jpg",
        galleryImages: [
            "/images/properties/property-5.jpg",
            "/images/properties/property-7.jpg",
            "/images/properties/property-3.jpg",
            "/images/properties/property-1.jpg",
        ],
        hostName: "Dilshan Fernando",
        hostBio: "Superhost · 5 years experience · Member since 2019",
        hostYears: 5,
        hostSuperhost: true,
        description:
            "A sensational over-water villa perched above the shimmering Bentota Lagoon, offering 360° water views from every room. Watch exotic kingfishers dive for fish from your private deck, jet ski across the lagoon at sunset, and cruise the river to the mangrove forest. An extraordinary intersection of river, lagoon, and ocean.",
        amenities: [
            { icon: "Wifi", label: "Free WiFi" },
            { icon: "Waves", label: "Lagoon Swimming" },
            { icon: "Wind", label: "Air Conditioning" },
            { icon: "Utensils", label: "Water-edge Dining" },
            { icon: "Bike", label: "Water Sports" },
            { icon: "ShieldCheck", label: "24hr Security" },
            { icon: "Coffee", label: "Morning Boat Tour" },
        ],
        reviewBreakdown: [
            { label: "Uniqueness", score: 5.0 },
            { label: "Cleanliness", score: 4.8 },
            { label: "Service", score: 4.9 },
        ],
        reviews: [
            {
                id: "r12-1",
                author: "Lucas Weber",
                avatarInitials: "LW",
                avatarColor: "#2E7D32",
                date: "1 month ago",
                text: "Waking up surrounded by water on all sides is something I'd dreamed about. The mangrove safari was magical.",
                rating: 5,
            },
            {
                id: "r12-2",
                author: "Nadia Kovač",
                avatarInitials: "NK",
                avatarColor: "#E65100",
                date: "6 weeks ago",
                text: "Dilshan's team made the most romantic anniversary surprise I could have imagined. We'll be back for our 10th for sure!",
                rating: 5,
            },
        ],
        rooms: [
            {
                id: "room-12-1",
                name: "Lagoon Water Villa",
                maxGuests: 2,
                bedType: "1 King Bed",
                sqft: 560,
                pricePerNight: 90_000,
                originalPrice: 110_000,
                tag: "Popular",
                features: ["Over-water deck", "Glass floor section", "Outdoor shower"],
                imageSrc: "/images/rooms/room-water-villa.jpg",
            },
            {
                id: "room-12-2",
                name: "Mangrove Sunset Suite",
                maxGuests: 4,
                bedType: "2 King Beds",
                sqft: 780,
                pricePerNight: 145_000,
                features: ["River-facing terrace", "Private boat dock", "Kitchenette"],
                imageSrc: "/images/rooms/room-grand-suite.jpg",
            },
        ],
        lat: 6.4218,
        lng: 80.0006,
    },
]

export function getPropertyById(id: string): PropertyDetail | undefined {
    return ALL_PROPERTIES.find(p => p.id === id)
}
